export const dictionaries = {
  en: {
    tabs_home: 'Home',
    tabs_workouts: 'Workouts',
    tabs_nutrition: 'Nutrition',
    tabs_progress: 'Progress',
    tabs_coach: 'Coach',
    tabs_community: 'Community',
    tabs_profile: 'Profile',
    tabs_settings: 'Settings',
    settings_title: 'Settings',
    settings_subtitle: 'Language, accessibility, voice, reminders, and account controls.',
    settings_preferences: 'Preferences',
    settings_language: 'Language',
    settings_language_auto: 'Auto-detect language',
    settings_language_desc: 'Use your device locale when available.',
    settings_dark_mode: 'Dark mode',
    settings_dark_mode_desc: 'Switch between light and dark appearance.',
    settings_high_contrast: 'High contrast mode',
    settings_high_contrast_desc: 'Boost contrast for stronger readability.',
    settings_large_text: 'Large text',
    settings_large_text_desc: 'Increase text size across shared UI components.',
    settings_font_scale: 'Text size',
    settings_voice: 'Voice & Audio',
    settings_voice_commands: 'Voice commands',
    settings_voice_commands_desc: 'Use supported voice input to navigate common areas.',
    settings_tts: 'Text to speech',
    settings_tts_desc: 'Read guidance aloud when supported on your device.',
    settings_preview_voice: 'Preview voice guidance',
    settings_try_voice: 'Try voice command',
    settings_voice_status: 'Voice status',
    settings_accessibility: 'Accessibility & Localization',
    settings_notifications: 'Notifications',
    settings_notifications_desc: 'Enable app notifications and reminders.',
    settings_unit_system: 'Unit System',
    settings_english: 'English',
    settings_urdu: 'Urdu',
    settings_metric: 'Metric',
    settings_imperial: 'Imperial',
    voice_preview_message: 'FITRACK accessibility preview is active.',
    voice_not_supported: 'Voice commands are available on supported web browsers only in this build.',
    voice_listening: 'Listening for a command...',
    voice_no_match: 'No supported command was recognized.',
    voice_command_home: 'Go home',
    voice_command_workouts: 'Open workouts',
    voice_command_nutrition: 'Open nutrition',
    voice_command_progress: 'Open progress',
    voice_command_community: 'Open community',
    voice_command_profile: 'Open profile',
    voice_command_settings: 'Open settings',
  },
  ur: {
    tabs_home: 'ہوم',
    tabs_workouts: 'ورک آؤٹس',
    tabs_nutrition: 'غذائیت',
    tabs_progress: 'پیش رفت',
    tabs_coach: 'کوچ',
    tabs_community: 'کمیونٹی',
    tabs_profile: 'پروفائل',
    tabs_settings: 'ترتیبات',
    settings_title: 'ترتیبات',
    settings_subtitle: 'زبان، رسائی، آواز، یاد دہانیاں، اور اکاؤنٹ کنٹرول۔',
    settings_preferences: 'ترجیحات',
    settings_language: 'زبان',
    settings_language_auto: 'زبان خودکار طور پر شناخت کریں',
    settings_language_desc: 'ممکن ہو تو ڈیوائس کی زبان استعمال کریں۔',
    settings_dark_mode: 'ڈارک موڈ',
    settings_dark_mode_desc: 'ہلکی اور گہری شکل کے درمیان تبدیل کریں۔',
    settings_high_contrast: 'ہائی کانٹراسٹ موڈ',
    settings_high_contrast_desc: 'زیادہ واضح مطالعہ کے لیے رنگوں کا فرق بڑھائیں۔',
    settings_large_text: 'بڑا متن',
    settings_large_text_desc: 'مشترکہ UI اجزا میں متن بڑا کریں۔',
    settings_font_scale: 'متن کا سائز',
    settings_voice: 'آواز اور آڈیو',
    settings_voice_commands: 'آواز کے کمانڈز',
    settings_voice_commands_desc: 'سپورٹڈ وائس ان پٹ سے عام حصوں میں جائیں۔',
    settings_tts: 'متن سے آواز',
    settings_tts_desc: 'ممکن ہو تو ہدایات بلند آواز میں سنائیں۔',
    settings_preview_voice: 'آواز کی مثال سنیں',
    settings_try_voice: 'وائس کمانڈ آزمائیں',
    settings_voice_status: 'آواز کی حالت',
    settings_accessibility: 'رسائی اور مقامی زبان',
    settings_notifications: 'اطلاعات',
    settings_notifications_desc: 'ایپ اطلاعات اور یاد دہانیاں فعال کریں۔',
    settings_unit_system: 'اکائی نظام',
    settings_english: 'انگریزی',
    settings_urdu: 'اردو',
    settings_metric: 'میٹرک',
    settings_imperial: 'امپیریل',
    voice_preview_message: 'فٹریک رسائی کی مثال فعال ہے۔',
    voice_not_supported: 'اس بلڈ میں وائس کمانڈز صرف سپورٹڈ ویب براؤزرز پر دستیاب ہیں۔',
    voice_listening: 'کمانڈ سن رہے ہیں...',
    voice_no_match: 'کوئی سپورٹڈ کمانڈ نہیں ملی۔',
    voice_command_home: 'ہوم کھولیں',
    voice_command_workouts: 'ورک آؤٹس کھولیں',
    voice_command_nutrition: 'غذائیت کھولیں',
    voice_command_progress: 'پیش رفت کھولیں',
    voice_command_community: 'کمیونٹی کھولیں',
    voice_command_profile: 'پروفائل کھولیں',
    voice_command_settings: 'ترتیبات کھولیں',
  },
} as const;

export type TranslationKey = keyof typeof dictionaries.en;
